-rm option added to docker run command so cleanups happen. Docker image also now mounts /output to local file system (configurable)

diff --git a/bin/qiime2_interactive b/bin/qiime2_interactive
--- a/bin/qiime2_interactive
+++ b/bin/qiime2_interactive
@@ -1,12 +1,40 @@
 #!/bin/bash
 
+# Set defaults
+LOCAL_BASE=''
+
+while getopts :l:c: opt; do
+  case $opt in
+    l)
+      LOCAL_BASE=$OPTARG
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+    :)
+      echo "Option -$OPTARG requires an argument." >&2
+      exit 1
+      ;;
+  esac
+done
+
 if [[ "$(docker images -q umigs/chiron-qiime2 2> /dev/null)" == "" ]]; then
   echo "Docker image for QIIME2 not found.  Downloading first ..."
 fi
 
-if [ ! -d "${HOME}/chiron/qiime2" ]; then
-    echo "Creating local output directory: ${HOME}/chiron/qiime2"
-    mkdir -p ${HOME}/chiron/qiime2
+if [ -z $LOCAL_BASE ]; then
+    if [ -w "/opt" ]; then
+        LOCAL_BASE="/opt/chiron/qiime2"
+    else
+        LOCAL_BASE="${HOME}/chiron/qiime2"
+    fi
 fi
 
-docker run -v ${HOME}/chiron/qiime2:/output -i -t umigs/chiron-qiime2 /bin/bash
+if [ ! -d ${LOCAL_BASE} ]; then
+    echo "Creating local output directory: ${LOCAL_BASE}"
+    mkdir -p ${LOCAL_BASE}
+fi
+
+echo "Saving files to /output in this Docker image will make them available in ${LOCAL_BASE} outside of it."
+docker run --rm -v ${LOCAL_BASE}:/output -i -t umigs/chiron-qiime2 /bin/bash
